# pull official base image
FROM node:alpine

# The /app directory should act as the main application directory
WORKDIR /app

# Copy the app package file
COPY package.json package.json

# Install node packages
RUN yarn install

# start app
CMD ["yarn", "run", "start"]