version: "3.11"

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
    volumes:
      - .\frontend\src:/app/src:ro

  backend:
    build: backend
    environment:
      PORT: 8000
      HOST: 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - .\backend\src:/app/src:ro
      - .\backend\uploads:/app/uploads
